name             'chef-stackdriver'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cic-stackdriver-agent'
long_description 'Installs/Configures cic-stackdriver-agent'
version          '0.1.0'
