name             'chef-sd'
maintainer       'veena dev'
maintainer_email 'veena.dev@reancloud.com'
license          'All rights reserved'
description      'Installs/Configures chef-sd'
long_description 'Installs/Configures chef-sd'
version          '0.1.0'
